sudo: required
services:
  - docker

before_install:
  - docker build -t lukeomalley/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lukeomalley/react-test npm test

after_success:
  - docker build -t lukeomalley/multi-client ./client
  - docker build -t lukeomalley/multi-nginx ./nginx
  - docker build -t lukeomalley/multi-server ./server
  - docker build -t lukeomalley/multi-worker ./worker

  # Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push lukeomalley/multi-client
  - docker push lukeomalley/multi-nginx
  - docker push lukeomalley/multi-server
  - docker push lukeomalley/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multicontainer-docker
  env: MulticontainerDocker-env
  bucket-name: elasticbeanstalk-us-east-1-296389209503
  bucket-path: docker-multicontainer
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
